-- schema owner
CREATE USER me WITH password 'me';

-- schema user
CREATE USER me_scheme WITH password 'me_scheme';

-- create schema
CREATE SCHEMA me AUTHORIZATION me;

GRANT USAGE ON SCHEMA me TO me_scheme;

ALTER DEFAULT PRIVILEGES FOR USER me IN SCHEMA me GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO me_scheme;
ALTER DEFAULT PRIVILEGES FOR USER me IN SCHEMA me GRANT USAGE ON SEQUENCES TO me_scheme;
ALTER DEFAULT PRIVILEGES FOR USER me IN SCHEMA me GRANT EXECUTE ON FUNCTIONS TO me_scheme;

ALTER USER me_scheme SET search_path = 'me';